<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSUAs1j5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSUAs1j5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSUAs1j5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSUAs1j5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSUAs1j5\App_KernelDevDebugContainer([
    'container.build_hash' => 'SUAs1j5',
    'container.build_id' => 'f6c97167',
    'container.build_time' => 1589892083,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSUAs1j5');
