<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerScwNh87\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerScwNh87/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerScwNh87.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerScwNh87\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerScwNh87\App_KernelDevDebugContainer([
    'container.build_hash' => 'ScwNh87',
    'container.build_id' => 'a0fb4f39',
    'container.build_time' => 1596832920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerScwNh87');
